%   tool_list = getSETToolList(data_type)
%
% Get list of tools available to apply to a voltage timeseries
function tool_list = getSETToolList(data_type)
   switch data_type
      case 'voltage'
         % Currently available tools to apply to voltage time series
         tool_list = {'Rescale',              ...
                      'Denoise',              ...
                      'Identify AP templates',...
                      'Extract spikes',       ...
                      'Utilities',            ...
                     };
                  
      case 'ap'
         tool_list = {'Extract spikes',       ...
                      'Merge templates',      ...
                     };
                  
      case 'spike'
         tool_list = {'Firing rate',          ...
                      'Statistics',           ...
                      'Spike operations',     ...
                     };
                  
      case 'rate'
         tool_list = {'Statistics',           ...
                     };
   end
