% GETTOOLTIPS Retrieves the list of all tooltips requested by objectName
%
% Syntax: str = getTooltips(objectName);
%
% Inputs:
%     objectName - Cell vector: String or strings containing the names of
%                  the objects for which to retrieve the tooltip.
%     
% Outputs:
%     str - Cell vector: String/s with the tooltip.
%
% Artemio - 11/July/2019
function str = getTooltips(objectName)
   % Create the list of all available tooltip strings
   tooltips = struct('load_voltage_button',  'Load a recording file (will remove all the currently loaded data)',...
      'add_voltage_button',                  'Load a new recording file. Doesn'' clear current data',...
      'clear_voltage_button',                'Removes currently active data',...
      'toggleZoomButton',                    'Zoom/Displace (toggle sliders function)',...
      'toggleZoomButton_toZoom',             'Toggle sliders function to Zoom (currently displacing)',...
      'toggleZoomButton_toDisplace',         'Toggle sliders function to Displace (currently zooming)',...
      'reset_button',                        'Reset zoom',...
      'time_slider',                         'Zoom/Displacement. Click arrows for a small jump. Click the bar for a big jump',...
      'voltage_slider',                      'Zoom/Displacement. Click arrows for a small jump. Click the bar for a big jump',...
      'new_figure',                          'Open a new ''Spike Extraction Tool'' window and loads currently active data',...
      'access_voltage',                      'Creates a variable in the Workspace with current data',...
      'set_tool_params',                     'Chose the paramaters for the selected tool',...
      'run_tool_button',                     'Run',...
      'run_tool_rescale',                    'Rescale: remove drift from current recording',...
      'run_tool_denoise',                    'Denoise: clean the recording',...
      'run_tool_identify_ap_templates',      'Identify templates',...
      'run_tool_extract_spikes',             'Extract spikes',...
      'run_tool_statistics',                 'Statistics',...
      'run_tool_merge_templates',            'Merge two or more templates',...
      'run_tool_delete_templates',           'Remove one or more templates',...
      'tool_list',                           'Chose an action',...
      'tool_list_rescale',                   sprintf('Chose an action\nRescale - remove drift from current recording'),...
      'tool_list_denoise',                   sprintf('Chose an action\nDenoise - remove noise'),...
      'tool_list_identify_ap_templates',     sprintf('Chose an action\nIdentify AP templates - Identify diferent action potential groups'),...
      'tool_list_extract_spikes',            sprintf('Chose an action\nExtract spikes - extract spikes from chosen recording'),...
      'tool_list_statistics',                sprintf('Chose an action\nStatistics - Explore the statistics of the extracted families'),...
      'tool_list_merge_templates',           sprintf('Chose an action\nMerge'),...
      'tool_list_delete_templates',          sprintf('Chose an action\nDelete template'),...
      'method_list',                         'Chose the method to run selected action',...
      'method_list_particle_filter',         sprintf('Chose the method to run selected action\nParticle Filter'),...
      'method_list_recursive_least_squares', sprintf('Chose the method to run selected action\nRecursive Least Squares'),...
      'method_list_k_means',                 sprintf('Chose the method to run selected action\nK-means'),...
      'method_list_matched_filter',          sprintf('Chose the method to run selected action\nMatched Filter'),...
      'method_list_amplitude_change',        sprintf('Chose the method to run selected action\nAmplitude Change'),...
      'method_list_user_selection',          sprintf('Chose the method to run selected action\nUser Selection (Manual)'),...
      'scroll_axes_slider',                  'Scroll down to view more templates',...
      'automatic_params',                    sprintf('If ticked, the parameters are set autmatically. \nUntick this box to set parameters manually.'),...
      'curr_signal',                         'Chose a signal to plot and analyse',...
      'save_voltage',                        'Save current data in a file');
   
   % Create output variable as an empty cell
   str = cell(1,length(objectName));
   
   for i = 1:length(objectName)
      try
         % Replace any space in the object name for an underscore
         objectName{i}(strfind(objectName{i}, ' ')) = '_';
         % Assign each tooltip string to the i-th cell. There will be i
         % output string cells for i input object names
         str{i} = tooltips.(objectName{i});
      catch
         % Most likely it didn't find the desired tooltip string
         % Return empty string.
         str{i} = '';
         % And print a message
         msgStr = sprintf('\tThe tooltip ''%s'' does not exist\n', objectName{i});
         printMessage('off', 'Text', msgStr);
      end
   end

end