% GETTOOLTIPS Retrieves the list of all tooltips requested by objectName
%
% Syntax: str = getTooltips(objectName);
%
% Inputs:
%     objectName - Cell vector: String or strings containing the names of
%                  the objects for which to retrieve the tooltip.
%     
% Outputs:
%     str - Cell vector: String/s with the tooltip.
%
% Artemio - 11/July/2019
function str = getTooltips(objectName)
   % Create the list of all available tooltip strings
   tooltips = struct('load_voltage', 'Load a recording file (will remove all the currently loaded data)',...
      'add_voltage',       'Load a new recording file. Doesn'' clear current data',...
      'clear_voltage',     'Removes currently active data',...
      'toggleZoomButton',  'Zoom/Displace (toggle sliders function)',...
      'time_slider',       'Zoom/Displacement. Click arrows for a small jump. Click the bar for a big jump',...
      'voltage_slider',    'Zoom/Displacement. Click arrows for a small jump. Click the bar for a big jump',...
      'new_figure',        'Open a new ''Spike Extraction Tool'' window and loads currently active data',...
      'access_voltage',    'Creates a variable in the Workspace with current data',...
      'set_tool_params',   'Chose the paramaters for the selected tool',...
      'run_tool',          'Run',...
      'run_tool_rescale',  'Rescale: remove drift from current recording',...
      'run_tool_denoise',  'Denoise: clean the recording',...
      'run_tool_identify_ap_templates',...
                           'Identify templates',...
      'run_tool_extract_spikes',...
                           'Extract spikes',...
      'tool_list',         'Chose an action',...
      'tool_list_rescale', sprintf('Chose an action\nRescale - remove drift from current recording'),...
      'method_list',       'Chose the method to run selected action',...
      'method_list_particle_filter',...
                           sprintf('Chose the method to run selected action\nParticle Filter'),...
      'method_list_recursive_least_squares',...
                           sprintf('Chose the method to run selected action\nRecursive Least Squares'),...
      'scroll_axes',       'Scroll down to view more templates',...
      'automatic_params',  sprintf('If ticked, the parameters are set autmatically. \nUntick this box to set parameters manually.'),...
      'save_voltage',      'Save current data in a file');
   
   % Create output variable as an empty cell
   str = cell(1,length(objectName));
   
   for i = 1:length(objectName)
      try
         % Replace any space in the object name for an underscore
         objectName{i}(strfind(objectName{i}, ' ')) = '_';
         % Assign each tooltip string to the i-th cell. There will be i
         % output string cells for i input object names
         str{i} = tooltips.(objectName{i});
      catch
         % Most likely it didn't find the desired tooltip string
         % Return empty string.
         str{i} = '';
         % And print a message
         msgStr = sprintf('\tThe tooltip ''%s'' does not exist\n', objectName{i});
         printMessage('off', 'Text', msgStr);
      end
   end

end